### ISSUE TITLE
NodeJS Websocket 发送事件后无响应

### ISSUE THREAD

**Issue by TTsdzb** [desu-life/Bot#2]
我在使用 [Lagrange.Onebot](https://github.com/LagrangeDev/Lagrange.Core) 连接 `ws://botws.desu.life:65000`。Bot 运行正常，但由于该软件没有 go-cqhttp 一样的过滤器，我使用 Typescript 与 [ws](https://www.npmjs.com/package/ws) 库写了一个中间件程序用于过滤事件的上报（代码在[这里](https://github.com/TTsdzb/onebot-ws-filter)）。

现在的问题是，中间件程序可以正常建立连接并将事件信息发送给服务端，但随后收不到任何回复。我尝试使用 Burpsuite 抓包，可以确定事件确实上报且发送出去了，内容也与没有中间件程序时完全相同，但服务端没有向我发送发消息的调用请求。

请问后台是否有报错等现象，或者我少做了什么吗？如果需要，我也可以提供额外的测试或信息。

**Comment by fantasyzhjk** [comment]
你的代理没有加onebot协议中的请求头，所以会被自动断开

**Comment by fantasyzhjk** [comment]
可以参考下
https://github.com/botuniverse/onebot-11/blob/refs%2Fheads%2Fmaster/communication%2Fws-reverse.md

**Comment by TTsdzb** [comment]
> 你的代理没有加onebot协议中的请求头，所以会被自动断开

这个是加了的：

```ts
const serverSocket = new WebSocket(config.reverseServerUrl, {
  headers: request.headers,
});
```

我试过，如果不加的话 Node 会无法解析响应然后直接报 `HPE_INVALID_CONSTANT` 退出，但现在的问题是连接可以正常维持，我没有收到 socket 关闭事件，也可以发送数据，但收不到回应

**Comment by fantasyzhjk** [comment]
仔细看了下代码，是没以 text 的形式发送数据导致的
发送的时候直接发送 string 类型，或者加个`{ binary: false }`的 option 就好

**Comment by TTsdzb** [comment]
> 仔细看了下代码，是没以 text 的形式发送数据导致的 发送的时候直接发送 string 类型，或者加个`{ binary: false }`的 option 就好

解决了，非常感谢
